### PR TITLE
Add logic directory | install big number

### PR DESCRIPTION
**Pull request by J2ZROMERO**
- Add files calculate.js and operate.js into a logic/ directory 
- Add  [big.js](https://www.npmjs.com/package/big-js) 
- Import the files in in the  Calculator component.
- Implement the event handlers you need to use the math logic from calculate.js and operate.js in your React component.
- Use state and props, pass props to child components
- Use lifecycle methods
- Lift state up.
- [LIVE VIEW](https://deploy-preview-3--sage-gaufre-cb8c5e.netlify.app/)

### CODE REVIEW

**Comment by J2ZROMERO** [comment]
- Add files calculate.js and operate.js into a logic/ directory 
- Add  [big.js](https://www.npmjs.com/package/big-js) 
- Import the files in in the  Calculator component.
- Implement the event handlers you need to use the math logic from calculate.js and operate.js in your React component.
- Use state and props, pass props to child components
- Use lifecycle methods
- Lift state up.

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @J2ZROMERO 🙋‍♀️,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project, that does not have a PR description. Please write a detailed PR description of what you did in this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by J2ZROMERO** [comment]
@KDlamini 
- Hello, sorry I pasted that in the comment section, I have fixed that, many thanks

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @J2ZROMERO, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 
- No linter errors
- correct flow is used
- good PR

## Required Changes ♻️

- [ ] Please update your README in order to look professional 👍 To be specific, there are unnecessary scripts that ship with React and other unnecessary information. Just stick with the Microverse template 😉 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by J2ZROMERO** [comment]
README.md updated

**Review by victorokoroji — APPROVED** [review]
Hi @J2ZROMERO, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
